### ISSUE TITLE
Should sys.getfilesystemencoding() return 'mbcs' now that this is a supported encoding?

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#141]
_From @ironpythonbot on December 9, 2014 17:37_

CPython does...  
## Work Item Details

**Original CodePlex Issue:**    [Issue 24220](http://ironpython.codeplex.com/workitem/24220)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Aug 5, 2009 at 10:40 PM
**Reported by:**    dfugate
**Updated on:** Nov 3 at 8:58 PM
**Updated by:** jdhardy
**Test:**   (CPy) test_support.py

_Copied from original issue: IronLanguages/main#731_

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:37_

On _2009-11-23 01:04:51 UTC_, **tkamiya** commented:

sys.getfilesystemencoding() returns None in 2.6 rc3. This breaks the following code:

import sys 
print "abc".decode(sys.getfilesystemencoding())

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:37_

On _2010-02-22 03:45:29 UTC_, **dinov** commented:

On Windows 9x, the encoding is “mbcs”. 
On Mac OS X, the encoding is “utf-8”. 
On Unix, the encoding is the user’s preference according to the result of nl_langinfo(CODESET), or None if the nl_langinfo(CODESET) failed.

On Windows NT+, file names are Unicode natively, so no conversion is performed. getfilesystemencoding() still returns 'mbcs', as this is the encoding that applications should use when they explicitly want to convert Unicode strings to byte strings that are
 equivalent when used as file names. 

We can easily do the Mac OS X and NT options. For all others we can check LANG env var at least as a 1st pass.

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:37_

On _2010-12-14 04:43:51 UTC_, **rjnienaber** commented:

For the record, sys.getfilesystemencoding() now returns an encoding: 

IronPython 2.7 Beta 1 (2.7.0.10) on .NET 4.0.30319.1

import sys
sys.getfilesystemencoding()
'mbcs'
print "abc".decode(sys.getfilesystemencoding())
abc

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:37_

On _2014-03-03 22:04:18 UTC_, **paweljasinski** commented:

the encoding is now hardcoded to 'mbcs' which I believe is wrong (left over from windows95 days?)
At the moment on my win7 with ntfs, I can create files containing euro(€), Latin-2 (Ł) or Latin-1 (ä) characters. When I throw them into encode with mbcs, only Latin-1 encodes into something reasonable. Other things end up as 0x63.

How about we change it on windows to UTF-16?

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:37_

On _2014-11-04 04:58:54 UTC_, **jdhardy** commented:

CPython uses mbcs on Windows in both 2.7 and 3.3. However, I don't think it works properly on IronPython:
IronPython 2.7.5b3 (2.7.5.0) on .NET 4.0.30319.34014 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.

> > > x = "euro(?), Latin-2 (L) or Latin-1 (ä)"
> > > x
> > > u'euro(\u20ac), Latin-2 (\u0141) or Latin-1 (\xe4)'
> > > x.decode('mbcs')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "ironlanguages\External.LCA_RESTRICTED\Languages\IronPython\27\Lib\encodings\mbcs.py", line 21, in decode
> > > UnicodeEncodeError: ('ascii', u'\u20ac', 5, 6, "'ascii' codec can't decode byte 20AC in position 5: ordinal not in range")
> > > with open(x, 'w') as f:
> > > ...     f.write(x)
> > > ...
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 2, in <module>
> > > UnicodeEncodeError: ('unknown', '\x00', 0, 1, "'ascii' codec can't encode character '\u20AC' in position 5")

**Comment by slide** [comment]
CPython 2.7 actually gets a similar error:

```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> x = u'euro(\u20ac), Latin-2 (\u0141) or Latin-1 (\xe4)'
>>> x.decode('mbcs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\encodings\mbcs.py", line 21, in decode
    return mbcs_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 5: ordinal not in range(128)
```
