### ISSUE TITLE
Create virtual environment in Visual Studio 2015 fails

### ISSUE THREAD

**Issue by Prodigio** [IronLanguages/ironpython2#229]
I'm trying to create an virtual environment in Visual Studio 2015 by right-clicking on Python Environments in my Python Project. But it ends with an error:

```
> Unhandled exception:
> Traceback (most recent call last):
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 13, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\exceptions.py", line 6, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 701, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 692, in exec_
> AttributeError: 'module' object has no attribute '_getframe'
> System.InvalidOperationException: Virtual environment was not created at 'C:\Users\Fred\Documents\Visual Studio 2015\Projects\Marty\MartyPython\env\'
>    at Microsoft.PythonTools.Project.VirtualEnv.<CreateAndInstallDependencies>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__148.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
```

This line: `AttributeError: 'module' object has no attribute '_getframe'` was leading me to set `-X:FullFrames` or `-X:Frames` in Visual Studio 2015 `Options > Python Tools > Interactive Windows > Interpreter Options` (for IronPython2.7). Unfortunately it doesn't work.

How to solve this? Am I missing something?

**Comment by slide** [comment]
This is a question for the Python Tools for Visual Studio folks at https://github.com/Microsoft/PTVS
