### ISSUE TITLE
Starting a Process fails with Attribute Error: WNOHANG not found

### ISSUE THREAD

**Issue by VinayGupta23** [IronLanguages/ironpython2#236]
Starting a `Process` fails with `Attribute Error: WNOHANG not found`.

### Example:

Example souce code used (refer [docs](https://ironpython-test.readthedocs.io/en/latest/library/multiprocessing.html#the-process-class)):

```python
from multiprocessing import Process
import os

def f(name):
    print 'hello', name

if __name__ == '__main__':
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

Output:
```console
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\multiprocessing\process.py", line 129, in start
  File "C:\Program Files (x86)\IronPython 2.7\Lib\multiprocessing\forking.py", line 114, in <module>
AttributeError: 'module' object has no attribute 'WNOHANG'
```

I am using IronPython's latest version:
`IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)`
My OS is a Windows 10 Enterprise.

**NOTE:** The same code executes without error on Python 2.7.13, with version:
`Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32`

  
I am looking forward to using IronPython extensively, and any support on this would be great.

Thanks,
Vinay

**Comment by slide** [comment]
Multiprocessing is not currently supported on IronPython

**Comment by VinayGupta23** [comment]
Oh, unfortunate to hear.

Is there is any plan to implement it in the near future or an alternative?

Regards,
Vinay

________________________________

**Comment by paweljasinski** [comment]
I hope I am not trivializing anything, but multiprocessing looks like low
hanging fruit.
It is full of sys.platform checks, which in case of ironpython take unix
instead of windows implementation.

**Comment by VinayGupta23** [comment]
I didn't quite understand what you're implying, and perhaps you could add more perspective to it.


Anyhow, I'll add some context to my problem. I need to load multiple instances of a `DLL` in my program, which is only permitted on different processes in Windows.

This is required as the DLL provides a UDP connection to some server, and due to limitations of the DLL (that I didn't write), I cannot connect to multiple ports concurrently on the same `DLL` instance.

Regards,
Vinay

________________________________

**Comment by slozier** [comment]
@VinayGupta23: I believe what @paweljasinski is saying is that there are a number of `if sys.platform == 'win32'` checks in the multiprocessing source file that should be changed to something like `if sys.platform == 'win32' or (sys.platform == 'cli' and os.name == 'nt')` to work with IronPython. These changes may (or may not) get the multiprocessing module up and running. PRs are welcome.

**Comment by slide** [comment]
@paweljasinski There is a native module (_multiprocessing) that needs to be implemented as well I believe.

**Comment by slide** [comment]
Multiprocessing isn't as important on IronPython since we don't have the GIL. You can still get usage of all cores in the system by using just the threading module on IronPython because the implementation underneath is the .NET framework, which will run on all processors and not have the GIL in play.
