### ISSUE TITLE
WeakRefTracker class is not thread safe

### ISSUE THREAD

**Issue by tinyg** [IronLanguages/ironpython2#266]
Hi All,

We have experienced a concurrency issue with OrderDicts which causes various errors including: "Index out of range", "weakref has gone away" and "array copy" exceptions.

This can be reproduced by creating lots of OrderDict instances in different threads at the same time. OrderDict uses the abc module, which in turn uses WeakSet to track metadata, which in turn uses weakrefs which seem to be the root cause.

Attached is a script which reproduces the issue (perhaps 1 in every 5 runs will fail). eg, in our local release version:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\threading.py", line 801, in _Thread__bo
otstrap_inner
    self.run()
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ironpython_weakref.py", line 37, in create_stuff
    [make_list() for _ in range(10)]
  File "ironpython_weakref.py", line 29, in make_list
    return collections.OrderedDict(
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\_abcoll.py", line 571, in update
    for key, value in other:
  File "ironpython_weakref.py", line 31, in <genexpr>
    for __ in range(8)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\abc.py", line 151, in __subclasscheck__

    if subclass in cls._abc_cache:
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\_weakrefset.py", line 72, in __contains
__
    wr = ref(item)
IndexError: Index was outside the bounds of the array.
```

and

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\threading.py", line 801, in _Thread__bo
otstrap_inner
    self.run()
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ironpython_weakref.py", line 37, in create_stuff
    [make_list() for _ in range(10)]
  File "ironpython_weakref.py", line 29, in make_list
    return collections.OrderedDict(
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\_abcoll.py", line 571, in update
    for key, value in other:
  File "ironpython_weakref.py", line 31, in <genexpr>
    for __ in range(8)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\_abcoll.py", line 564, in update
    if isinstance(other, Mapping):
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\abc.py", line 132, in __instancecheck__

    if subclass is not None and subclass in cls._abc_cache:
  File "C:\TFS\SDKS\ironpython\2.7.7\Lib\_weakrefset.py", line 75, in __contains
__
    return wr in self.data
TypeError: weak object has gone away

```

Looking at the code in WeakRef.cs, I can see that the _callbacks list is not thread safe which lines up with the stack traces in VisualStudio when debugging these issues.

I have made a tentative patch in my local fork to wrap access to the _callback list with a ReaderWriterLockSlim which seems to fix the issue (ie 20 runs without any errors). But I'm not certain if that is the correct fix as I'm really just patching the symptom - perhapss this would have some vast performance penalty?

Happy to provide any further info or submit a PR with my change if that helps.

Cheers
Chris
[ironpython_weakref.zip](https://github.com/IronLanguages/ironpython2/files/1490318/ironpython_weakref.zip)

**Comment by tinyg** [comment]
BTW, I also see a comment in Languages\IronPython\Tests\test_weakref.py saying:

## * Issues of the current implementation of _weakref.cs:
##
##    - weakref finalization callbacks are run in the CLR finalizer thread. 
##      This is likely to cause data races in user code.
##    - WeakRefTracker.cs code and internal state handling most likely is not
##      implemented in a thread-safe way.

Which seems to agree with the spirit of the suggested fix.

**Comment by tinyg** [comment]
Pull request added with my suggested fix.
