### ISSUE TITLE
DistutilsPlatformError: Python was built with Visual Studio version 6

### ISSUE THREAD

**Issue by fossum** [IronLanguages/ironpython2#305]
I'm having an issue installing CFFI. Seems something was compiled with VC++6 and I have no idea what to install to support that.

```
C:\Program Files (x86)\IronPython 2.7>Scripts\pip.exe install cffi
Collecting cffi
c:\program files (x86)\ironpython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
  Using cached cffi-1.11.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ericfoss\appdata\local\temp\pip-build-zykoci\cffi\setup.py", line 138, in <module>
      File "c:\users\ericfoss\appdata\local\temp\pip-build-zykoci\cffi\setup.py", line 66, in ask_supports_thread
      File "c:\program files (x86)\ironpython 2.7\Lib\distutils\command\config.py", line 232, in try_compile
      File "c:\program files (x86)\ironpython 2.7\Lib\distutils\command\config.py", line 138, in _compile
      File "c:\program files (x86)\ironpython 2.7\Lib\distutils\msvccompiler.py", line 353, in compile
      File "c:\program files (x86)\ironpython 2.7\Lib\distutils\msvccompiler.py", line 266, in initialize
    distutils.errors.DistutilsPlatformError: Python was built with Visual Studio version 6, and extensions need to be built with the same version of the compiler, but it isn't installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ericfoss\appdata\local\temp\pip-build-zykoci\cffi\
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Program Files (x86)\IronPython 2.7>
```

I have Visual Studio Enterprise 2017 with every C/C++ thing I could find installed. Am I suppose to run this through Cygwin or something?

**Comment by slide** [comment]
cffi a native extension, which means it can't be used with IronPython.

**Comment by fossum** [comment]
Oh, is there an IronPython equivalent?

**Comment by slide** [comment]
You can use the clrtype module to do P/Invoke, see this example from our test suite https://github.com/IronLanguages/ironpython2/blob/master/Tests/test_clrtype.py#L98
