### ISSUE TITLE
threading.py _newname throws StopIteration

### ISSUE THREAD

**Issue by obiben** [IronLanguages/ironpython2#314]
With the new way to generate names when initializing a thread (itertool's count, and calling next) we run into a chance of getting an exception thrown.

Here an example from logs:

```
10:42:13.874 - Traceback (most recent call last):
10:42:13.875 -   File "C:\platform\tickets.py", line 221, in _ScheduleUpdate
10:42:13.875 -     self._UpdateTimer = threading.Timer(smoothTime, self._UpdateOrder)
10:42:13.875 -   File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 1047, in Timer
10:42:13.875 -     return _Timer(*args, **kwargs)
10:42:13.875 -   File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 1059, in __init__
10:42:13.875 -     Thread.__init__(self)
10:42:13.875 -   File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 675, in __init__
10:42:13.875 -     self.__name = str(name or _newname())
10:42:13.875 -   File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 621, in _newname
10:42:13.875 -     return template % _counter()
10:42:13.875 - StopIteration
```

**Comment by slide** [comment]
Can you provide a repro case?

**Comment by obiben** [comment]
Been thus far unable to do so. Do you happen to know where I could find the source for itertools?

**Comment by slozier** [comment]
The itertools.count issue has been mentioned before (https://github.com/IronLanguages/ironpython2/issues/210#issuecomment-315263733). There seems to be some sort of workaround in the gist however I don't see how it could possibly work.
