### ISSUE TITLE
Interpreter keywords not recognized: "Type "help", "copyright", "credits" or "license" for more information." 

### ISSUE THREAD

**Issue by rtzoeller** [IronLanguages/ironpython2#350]
IronPython prints out the same initial message as CPython when the interpreter is launched:

"Type "help", "copyright", "credits" or "license" for more information."

However, none of these keywords are recognized/have the correct behavior.

```
IronPython 2.7.8 (2.7.8.0) on Mono 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> help
<built-in function help>
>>> copyright
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'copyright' is not defined
>>> credits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'credits' is not defined
>>> license
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'license' is not defined
```

```
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help
Type help() for interactive help, or help(object) for help about object.
>>> copyright
Copyright (c) 2001-2014 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.
>>> credits
    Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information.
>>> license
Type license() to see the full license text
```

**Comment by slozier** [comment]
Is this a Mono issue? On Windows I get:
```
IronPython 2.7.8 (2.7.8.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> help
Type help() for interactive help, or help(object) for help about object.
>>> copyright
Copyright (c) IronPython Team
>>> credits
IronPython is maintained by the IronPython developers (www.ironpython.net).
>>> license
Type license() to see the full license text
```

**Comment by rtzoeller** [comment]
Interestingly it looks like IronPython2 from an official install works (same behavior as what you posted), but with local builds (both Mono and Windows for me) it doesn't. Just tested on the latest master on Windows.

```
IronPython 2.7.8b1 (2.7.8.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> help
<built-in function help>
>>> copyright
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'copyright' is not defined

>>> credits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'credits' is not defined

>>> license
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'license' is not defined
```

It's possible something is wrong with my build setup.

**Comment by slozier** [comment]
It sounds like the standard library isn't being loaded. The release build does not pick up the std lib folder automatically. One option would be to set the IRONPYTHONPATH environment variable to point to the lib folder.
