### ISSUE TITLE
Pytest doesn't work with IronPython

### ISSUE THREAD

**Issue by scaramallion** [IronLanguages/ironpython2#356]
Apologies if this is something stupid, I don't have much experience with `ctypes`. I'm trying to figure out why pytest doesn't work with a new install of IronPython 2.7.7 and it seems like `ctypes.pythonapi` is missing some of its API functions. The following is adapted from [here](https://github.com/IronLanguages/ironpython2/blob/master/Src/StdLib/Lib/ctypes/test/test_python_api.py):
```python
>>> import ctypes
>>> ctypes.pythonapi.PyString_FromStringAndSize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\ctypes\__init__.py", line 375, in __getattr__
  File "C:\Program Files (x86)\IronPython 2.7\Lib\ctypes\__init__.py", line 380, in __getitem__
AttributeError: function PyString_FromStringAndSize is not defined
```
Windows 10, IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)

**Comment by slide** [comment]
The c API is not necessarily something we will implement. Also, please use 2.7.8

**Comment by mrbean-bremen** [comment]
Does that mean that pytest will not work with IronPython, or is there a workaround you know about?

**Comment by scaramallion** [comment]
The IronPython2.7.8 [msi installer](https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.8) is missing a bunch of files (including ipy.exe)

**Comment by slide** [comment]
If pytest requres the C API, then it will not work with IronPython.

**Comment by mrbean-bremen** [comment]
@slide - thanks, we are out of luck with pytest then. 
@scaramallion - I used the 2.7.8 msi installer a few weeks ago and it worked fine (no luck with pytest though) - maybe your download was incomplete or something like that.

**Comment by slide** [comment]
I'd like to have this open but change the title

**Comment by slozier** [comment]
You can probably try to work around the missing ctypes.pythonapi issue. It's only used in attr\_compat.py (the attrs package).

**Comment by slide** [comment]
It still doesn't work, even after doing that

**Comment by EmmanuelTramoy** [comment]
Hello,

I'd like to confirm that pytest is not working on several versions of IronPython, I saw the issue already opened, I hope my investigations will help :

- Tested with version 2.7.4  - no pip - no setup tools - impossible for me to install properly
- Tested with versions 2.7.5/2.7.9 - raw config parser error

![275-279RawConfigParser](https://user-images.githubusercontent.com/53532934/62228418-ea251380-b3bd-11e9-8175-1b7cfc6b69c2.png)

- Tested also with 2.7.5/2.7.9 with [IronPython pytest dedicated branch](https://bitbucket.org/dahlia/pytest-ironpython/src/default/setup.py) manual setup.py install

I/O Operation error
![capture pyIronPytest](https://user-images.githubusercontent.com/53532934/62228576-3c663480-b3be-11e9-9de6-c95b78e842cf.png)

Tested with the X:Frames command  [as explained here :](https://ironpython.net/blog/2014/12/06/ironpython-275-released.html)

Unable to fetch the good version of pytest or pip.
![xframespip](https://user-images.githubusercontent.com/53532934/62228803-b26a9b80-b3be-11e9-9053-4b765175aa82.png)
![xframespytest](https://user-images.githubusercontent.com/53532934/62228804-b26a9b80-b3be-11e9-8911-619f6ade2888.png)

Forgive me for not knowing the git-hub netiquette, this is my first time posting here. 
Have a good day!

**Comment by slozier** [comment]
@EmmanuelTramoy Thanks for the feedback.

The `RawConfigParser` issue is likely the same as https://github.com/IronLanguages/ironpython3/issues/546. I believe you could bypass this by getting rid of the comments in the regex strings of `backports\configparser\__init__.py`.

Not sure about the `I/O operation on closed file` issue.

**Comment by EmmanuelTramoy** [comment]
@slozier   Thanks very much, it is indeed solving the issue for this particual problem.
I am now falling back to the I/O issue unfortunately:

```powershell
PS C:\Users\etramoy> & "C:\Users\etramoy\Documents\Tests\OfficialIronPython\ipy.exe" -m pytest
Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 187, in run_module
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\_pytest\config\__init__.py", line 63, in main
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\_pytest\config\__init__.py", line 206, in _prepareconfig
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 72, in _run_code
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pytest.py", line 102, in <module>
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pluggy\hooks.py", line 289, in __call__
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pluggy\manager.py", line 87, in _hookexec
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pluggy\manager.py", line 78, in <lambda$257>
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pluggy\callers.py", line 203, in _multicall
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\_pytest\helpconfig.py", line 94, in pytest_cmdline_parse
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\site-packages\pluggy\callers.py", line 81, in get_result
  File "<string>", line 3, in _reraise
ValueError: I/O operation on closed file
```

**Comment by slozier** [comment]
@EmmanuelTramoy Did a bit of digging and it looks like the issue is essentially the same as https://github.com/IronLanguages/ironpython2/issues/92. The whole file descriptor handling of IronPython is unfortunately somewhat problematic... Was able to get around it by removing the `with f:` in `_pytest\capture.py`:
```Python
f = TemporaryFile()
with f: # remove this line!
    tmpfile = ...
```

It then failed with `TypeError: data must be str, not bytes` somewhere which is likely because `str == unicode` with IronPython 2.7 (instead of the `str == bytes` of CPython 2.7).

Perhaps the `pytest-ironpython` branch you linked above works around some of these issues?

**Comment by EmmanuelTramoy** [comment]
@slozier ok we advance but still kinda stuck here, but maybe can you can give some insights.
I installed the Iron python version with `pip install .` in the official release of IronPython 2.7.9 []((https://bitbucket.org/dahlia/pytest-ironpython/src))
Launch pytest, have the following error as expected :

```powershell
PS C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366> & "C:\Users\etramoy\Documents\Tests\OfficialIronPython\ipy.exe" -m pytest
Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 187, in run_module
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 628, in pytest_cmdline_parse
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 702, in _preparse
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 412, in __call__
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\capture.py", line 69, in _getcapture
  File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\runpy.py", line 72, in _run_code
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\pytest.py", line 10, in <module>
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 28, in main
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 80, in _prepareconfig
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 412, in __call__
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 423, in _docall
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 314, in execute
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\helpconfig.py", line 27, in pytest_cmdline_parse
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 314, in execute
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 731, in parse
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 423, in _docall
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 314, in execute
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\capture.py", line 51, in pytest_load_initial_conftests
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\capture.py", line 79, in init_capturings
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\capture.py", line 252, in __init__
  File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\capture.py", line 336, in __init__
ValueError: I/O operation on closed file
```

Then I did the modification in capture.py and it indeed unlocked the issue, but know I found another one :
```powershell
PS C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366> & "C:\Users\etramoy\Documents\Tests\OfficialIronPython\ipy.exe" -m pytest
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\main.py", line 77, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 610, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 412, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 423, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 314, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\__init__.py", line 60, in pytest_configure
INTERNALERROR>     _load_modules(mode)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\__init__.py", line 141, in _load_modules
INTERNALERROR>     from _pytest.assertion import reinterpret  # noqa
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\reinterpret.py", line 50, in <module>
INTERNALERROR>     from _pytest.assertion.oldinterpret import interpret as reinterpret_old
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\oldinterpret.py", line 3, in <module>
INTERNALERROR>     from compiler import parse, ast, pycodegen
INTERNALERROR> ImportError: No module named compiler
```

From what I understand, it is missing the compiler module, so for the sake of testing I tried to copy the compiler folder from the official Python (not IronPython) 2.7.9 and then :

```powershell
PS C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366> & "C:\Users\etramoy\Documents\Tests\OfficialIronPython\ipy.exe" -m pytest
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\main.py", line 77, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\config.py", line 610, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 412, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 423, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\core.py", line 314, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\__init__.py", line 60, in pytest_configure
INTERNALERROR>     _load_modules(mode)
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\__init__.py", line 141, in _load_modules
INTERNALERROR>     from _pytest.assertion import reinterpret  # noqa
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\reinterpret.py", line 50, in <module>
INTERNALERROR>     from _pytest.assertion.oldinterpret import interpret as reinterpret_old
INTERNALERROR>   File "C:\Users\etramoy\Downloads\dahlia-pytest-ironpython-bd8990f67366\_pytest\assertion\oldinterpret.py", line 3, in <module>
INTERNALERROR>     from compiler import parse, ast, pycodegen
INTERNALERROR>   File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\compiler\__init__.py", line 27, in <module>
INTERNALERROR>     from compiler.transformer import parse, parseFile
INTERNALERROR>   File "C:\Users\etramoy\Documents\Tests\OfficialIronPython\Lib\compiler\transformer.py", line 29, in <module>
INTERNALERROR>     import parser
INTERNALERROR> ImportError: No module named parser
```
I'm pretty sure it's talking about this [parser](https://docs.python.org/3.0/library/parser.html), but I cannot seem to find a corresponding file, doc is talking about "built'in" python module, maybe it's not accessible? I can't seem to see a matching name with matching functions (expr(), suite())

Thanks a lot for your help !

**Comment by slozier** [comment]
Unfortunately the `parser` built-in module is not implemented in IronPython so trying to use that old `pytest-ironpython` branch may be a dead end.

I've had some success with the latest pytest:
1. `ipy -m pip install pytest`
2. remove the comments from the regex in `backports\configparser\__init__.py`
3. remove the `with f:` in `_pytest\capture.py`
4. replace `isinstance(data, six.binary_type)` with `isinstance(data, (bytes, six.binary_type))` in `pathlib2\__init__.py`
5. `ipy -m pytest`

**Comment by EmmanuelTramoy** [comment]
@slozier Nice it's working on my side thanks !I just had to update to a later version of pip (18.1) to not have deprecation warnings. Also the tests take twice as long but it's working.
I'm not used to the working model here? Should I make a branch, try to push the changes for a PR?

Thanks a lot again for helping !

**Comment by slozier** [comment]
@EmmanuelTramoy Hmm, I'm not sure since these tweaks involve multiple 3rd party packages (configparser, pytest, pathlib2). I guess you could maintain a branch with the tweaks and all the dependencies?

Changes 2 and 3 could be addressed on the IronPython side of things by fixing the issues I referenced in previous comments. The changes required because `str == unicode` (such as 4) are more problematic and would probably ipy specific code in each of the 3rd party package where these issues occur.

Some other issues I ran into when testing:
- `_pytest\warnings.py`: `warning_record_to_str` can get stuck in a loop and crash, was able to bypass by getting rid of the `if compat._PY2` block.
- `_pytest\python.py`: in `hasinit` changed to `init != object.__init__` to `init is not object.__init__`. Cause by https://github.com/IronLanguages/ironpython2/issues/650
