### ISSUE TITLE
`pip` should work after installation without needing to run `ipy -m ensurepip`

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#381]
CPython Windows (and OSX) installers invoke `ensurepip` automatically as explained in [PEP-477](https://www.python.org/dev/peps/pep-0477/). IronPython Windows installer should do the same.

**Comment by slide** [comment]
I believe I have a fix for this, I'll continue testing.

**Comment by tarlano** [comment]
When do you expect to release 2.7.9?

**Comment by slide** [comment]
My hope is within the next two weeks.

**Comment by Nodirbek9204** [comment]
> I believe I have a fix for this, I'll continue testing.

I am new python learner

Whey I try to install any package for ironpython I am into trouble like:
******************************************************************************
C:\Program Files\IronPython 2.7> ipy -m pip install matplotlib
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 107, in _get_module_
details
ImportError: No module named pip
*********************************************************************************
or next
*************************************************************************
C:\Program Files\IronPython 2.7>ipy -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Exception:
Traceback (most recent call last):
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\utils\logging.py", line 36, in indent_log
    yield
KeyError: а
************************************************************************************************
or next
**********************************************************************************************
C:\Program Files\IronPython 2.7>ipy -X:Frames -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Exception:
Traceback (most recent call last):
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\utils\logging.py", line 36, in indent_log
    yield
KeyError: а
*****************************************************************************************
During installation of Ironpython "pip" was selected to be installed.
I supposed pip was not installed for ironpython, after that i tried install it from local folder:

C:\Program Files\IronPython 2.7>ipy c:\pip-8.1.1-py2.py3-none-any.whl install
can't find '__main__' module in 'c:\pip-8.1.1-py2.py3-none-any.whl'
***************************************************************************************
I tried different version of pip, but no success!!!
**************************************************************************************
pip on python works very well, packades are easely installing, problem only with ironpython.
also, I tried different verisons of ironpython, no positive result. Can any body halp me? Please!!!!




CMD runed as a admin
Windows 7   64 bit


**IronPython version:**
 C:\Program Files\IronPython 2.7>ipy -V
IronPython 2.7.9 2.7.9.0 on .NET 4.0.30319.42000

**python version**
c:\>py -V
Python 3.5.2

**pip verson on python**
c:\>py -m pip -V
pip 8.1.1 from C:\Program Files\Python35\lib\site-packages (python 3.5)

**pip version on ipy**
C:\Program Files\IronPython 2.7>ipy -m pip -V
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 107, in _get_module_
details
ImportError: No module named pip
