### ISSUE TITLE
ctypes/test/test_pointers .py fails

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#389]
```
======================================================================
FAIL: test_pointers (__main__.AsParamPropertyWrapperTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_as_parameter.py", line 46, in test_pointers
    self.assertEqual(result.contents.value, 42)
AssertionError: 800442112 != 42

======================================================================
FAIL: test_pointers (__main__.AsParamWrapperTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_as_parameter.py", line 46, in test_pointers
    self.assertEqual(result.contents.value, 42)
AssertionError: 1254194384 != 42

======================================================================
FAIL: test_pointers (__main__.BasicWrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_as_parameter.py", line 46, in test_pointers
    self.assertEqual(result.contents.value, 42)
AssertionError: 1254210640 != 42
```

**Comment by slide** [comment]
This also affects test_functions.py in ctypes\test

**Comment by slide** [comment]
Collected in #457
