### ISSUE TITLE
Issue in ctypes\test\test_strings.py

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#398]
```python
def test_c_buffer_deprecated(self):
        # Compatibility with 2.x
        with test_support.check_py3k_warnings():
            self.test_c_buffer_value(buffer)
            self.test_c_buffer_raw(buffer)
```

```
======================================================================
FAIL: test_c_buffer_deprecated (__main__.StringArrayTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\acearl\Code\_ipy\ironpython2\Src\StdLib\Lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\acearl\Code\_ipy\ironpython2\Src\StdLib\Lib\test\support\__init__.py", line 944, in _filterwarnings
    yield WarningsRecorder(w)
AssertionError: TypeError not raised
```

**Comment by slide** [comment]
Collected in #457
