### ISSUE TITLE
ctypes\test\test_parameters.py is failing

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#401]
```
F.FFFFFsE..
======================================================================
ERROR: test_noctypes_argtype (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 158, in test_noctypes_argtype
    self.assertEqual(func(None), None)
NotImplementedError: The method or operation is not implemented.

======================================================================
FAIL: test_abstract (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 182, in test_abstract
    self.assertRaises(TypeError, Array.from_param, 42)
AssertionError: TypeError not raised

======================================================================
FAIL: test_byref_pointer (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 112, in test_byref_pointer
    self.assertRaises(TypeError, LPINT.from_param, byref(c_short(22)))
AssertionError: TypeError not raised

======================================================================
FAIL: test_byref_pointerpointer (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 124, in test_byref_pointerpointer
    self.assertRaises(TypeError, LPLPINT.from_param, byref(pointer(c_short(22))))
AssertionError: TypeError not raised

======================================================================
FAIL: test_cstrings (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 59, in test_cstrings
    self.assertIs(c_char_p.from_param(s)._obj, s)
AssertionError: c_char_p('123') is not '123'

======================================================================
FAIL: test_cw_strings (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 82, in test_cw_strings
    self.assertRaises(UnicodeDecodeError, c_wchar_p.from_param, "123\377")
AssertionError: UnicodeDecodeError not raised

======================================================================
FAIL: test_int_pointers (__main__.SimpleTypesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_parameters.py", line 97, in test_int_pointers
    self.assertEqual(LPINT.from_param(None), None)
AssertionError: 0 != None

----------------------------------------------------------------------
Ran 11 tests in 0.318s

FAILED (failures=6, errors=1, skipped=1)
```

**Comment by slide** [comment]
Collected in #457
