### ISSUE TITLE
ctypes\test\test_unicode.py is failing

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#405]
```
FFFF.F.FF.
======================================================================
FAIL: test_ascii_ignore (__main__.StringTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 108, in test_ascii_ignore
    self.assertEqual(func(u"äöüß"), "")
AssertionError: u'\xe4\xf6\xfc\xdf' != ''
- äöüß
+


======================================================================
FAIL: test_ascii_replace (__main__.StringTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 115, in test_ascii_replace
    self.assertEqual(func(u"äöüß"), "????")
AssertionError: u'\xe4\xf6\xfc\xdf' != '????'
- äöüß
+ ????


======================================================================
FAIL: test_ascii_strict (__main__.StringTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 28, in test_ascii_strict
    self.assertRaises(ctypes.ArgumentError, wcslen, "abä")
AssertionError: ArgumentError not raised

======================================================================
FAIL: test_buffers (__main__.StringTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 124, in test_buffers
    self.assertEqual(buf[:], "ab???\0")
AssertionError: u'ab\xe4\xf6\xfc\x00' != 'ab???\x00'
- abäöü
+ ab???


======================================================================
FAIL: test_ascii_ignore (__main__.UnicodeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 45, in test_ascii_ignore
    self.assertEqual(wcslen("äöüß"), 0)
AssertionError: 4 != 0

======================================================================
FAIL: test_ascii_strict (__main__.UnicodeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 28, in test_ascii_strict
    self.assertRaises(ctypes.ArgumentError, wcslen, "abä")
AssertionError: ArgumentError not raised

======================================================================
FAIL: test_buffers (__main__.UnicodeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\Src\StdLib\Lib\ctypes\test\test_unicode.py", line 62, in test_buffers
    self.assertEqual(buf[:], u"ab\uFFFD\uFFFD\uFFFD\0")
AssertionError: u'ab\xe4\xf6\xfc\x00' != u'ab\ufffd\ufffd\ufffd\x00'
- abäöü
+ ab???


----------------------------------------------------------------------
Ran 10 tests in 0.457s

FAILED (failures=7)
```

**Comment by slide** [comment]
Collected in #457
