### ISSUE TITLE
import typing fails

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#414]
`typing` module fails to import with IronPython. Here's the error:
> import typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\typing.py", line 1788, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\abc.py", line 109, in register
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\typing.py", line 1249, in \_\_subclasscheck\_\_
  File "C:\Program Files\IronPython 2.7\Lib\abc.py", line 154, in \_\_subclasscheck\_\_
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\typing.py", line 1128, in _abc_negative_cache_version
AttributeError: 'GenericMeta' object has no attribute '_abc_generic_negative_cache_version'

The issue appears to be something like this:
```Python
x = [0]

class TestA(type):
    def __new__(mcls, name, bases, namespace):
        cls = super(TestA, mcls).__new__(mcls, name, bases, namespace)
        cls.a = 2
        return cls

class TestB(TestA):
    def __new__(cls, name, bases, namespace):
        return super(TestB, cls).__new__(cls, name, bases, namespace)
    def __setattr__(self, attr, value):
        x[0] = value

class TestC(object):
    __metaclass__ = TestB

TestC()

assert x[0] == 2
```

**Comment by slozier** [comment]
Looks like there's also an interaction with setters so it's more complicated than above:
```Python
class Test(type):
    def __new__(cls, name, bases, namespace):
        cls = super(Test, cls).__new__(cls, name, bases, namespace)
        cls.a = 10
        assert not hasattr(cls, "a")
        cls.test = 10
        assert cls.test == 10
        return cls        

    @property
    def test(self):
        return self._test

    @test.setter
    def test(self, value):
        self._test = value

    def __setattr__(self, attr, value):
        if attr in ("test", "_test"):
            super(Test, self).__setattr__(attr, value)

class TestMeta(object):
    __metaclass__ = Test
```

**Comment by datalogics-robb** [comment]
Is there a workaround or fix in Ipy3?
