### ISSUE TITLE
test_system_timers is not stable on macOS

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#469]
Sometimes get failures like the below:

```
2018-07-21T15:50:20.9035980Z IronPythonCases.test_system_timers
2018-07-21T15:50:27.4168340Z Unhandled exception on thread
2018-07-21T15:50:27.4221480Z Traceback (most recent call last):
2018-07-21T15:50:27.4237000Z   File "/Users/vsts/agent/2.136.1/work/1/s/Tests/test_system_timers.py", line 71, in test_sanity
2018-07-21T15:50:27.4252750Z   File "/Users/vsts/agent/2.136.1/work/1/s/Tests/test_system_timers.py", line 61, in timer_helper
2018-07-21T15:50:27.4268490Z   File "/Users/vsts/agent/2.136.1/work/1/s/Src/StdLib/Lib/unittest/case.py", line 428, in assertTrue
2018-07-21T15:50:27.4283820Z AssertionError: 2 is not >= 3
2018-07-21T15:50:28.2736510Z Traceback (most recent call last):
2018-07-21T15:50:28.2752120Z   File "/Users/vsts/agent/2.136.1/work/1/s/Tests/test_system_timers.py", line 271, in <module>
2018-07-21T15:50:28.2768150Z   File "/Users/vsts/agent/2.136.1/work/1/s/bin/Release/net45/Lib/iptest/ipunittest.py", line 356, in run_test
2018-07-21T15:50:28.2783990Z   File "/Users/vsts/agent/2.136.1/work/1/s/Src/StdLib/Lib/test/support/__init__.py", line 1626, in run_unittest
2018-07-21T15:50:28.2805850Z   File "/Users/vsts/agent/2.136.1/work/1/s/Src/StdLib/Lib/test/support/__init__.py", line 1545, in _run_suite
2018-07-21T15:50:28.2821760Z test.support.TestFailed: Traceback (most recent call last):
2018-07-21T15:50:28.2837480Z   File "/Users/vsts/agent/2.136.1/work/1/s/Tests/test_system_timers.py", line 95, in test_multiple_events_one_timer
2018-07-21T15:50:28.2853060Z     self.timer_helper(num_handlers=5)
2018-07-21T15:50:28.2868550Z   File "/Users/vsts/agent/2.136.1/work/1/s/Tests/test_system_timers.py", line 61, in timer_helper
2018-07-21T15:50:28.2886900Z     self.assertTrue(COUNT >= int(sleep_time - sleep_time*error_margin) * (num_handlers+len(event_handlers)), '%d is not >= %d' % (COUNT, int(sleep_time - sleep_time*error_margin) * (num_handlers+len(event_handlers))))
2018-07-21T15:50:28.2904490Z AssertionError: 10 is not >= 15
```

**Comment by slozier** [comment]
Just on Mono or .NET Core as well?

**Comment by slide** [comment]
I think its just on Mono, I believe I saw this before but didn't get a chance to look into it.
