### ISSUE TITLE
Exception traceback incorrect within a context manager

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#493]
The exception traceback is incorrect within a context manager. Very annoying when trying to debug pip failures.

Repro code:
```
import contextlib

@contextlib.contextmanager
def test_context():
    try:
        yield
    finally:
        pass

def test():
    def testA():
        testB()
    def testB():
        testC()
    def testC():
        raise Exception
    with test_context():
        testA()

test()
```
Expected traceback:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in test
  File "<stdin>", line 3, in testA
  File "<stdin>", line 5, in testB
  File "<stdin>", line 7, in testC
Exception

Actual traceback:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Lib\contextlib.py", line 35, in \_\_exit\_\_
  File "<stdin>", line 4, in test_context
Exception

**Comment by slozier** [comment]
Simplified repro:
```Python
import sys

def gen_exc(type, value, traceback):
    def generator(): yield
    gen = generator()
    try:
        gen.throw(type, value, traceback)
    except:
        pass

try:
    raise Exception
except:
    gen_exc(*sys.exc_info())
    raise
```
Expected traceback:
> Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception

Actual traceback:
> Traceback (most recent call last):
  File "<stdin>", line 5, in gen_exc
  File "<stdin>", line 0, in generator
Exception

**Comment by slozier** [comment]
Ok, I think the underlying issue is that our frames/traceback are stored in our exceptions so when an exception gets rethrown the original traceback gets clobbered. Here's the final repro:
```Python
def trycatch(e):
    try:
        raise e
    except:
        pass

try:
    raise Exception
except Exception as e:
    trycatch(e)
    raise
```
Expected traceback:
> Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception

Actual traceback:
>Traceback (most recent call last):
  File "<stdin>", line 3, in trycatch
Exception
