### ISSUE TITLE
`re.compile(r"\'%s\'" % (sys.maxint + 1))` fails with parse error

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#515]
To reproduce:

```python
E:\>ipy
IronPython 2.7.9rc1 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import re, sys
>>> re.compile(r"\'%s\'" % sys.maxint)
<RE_Pattern object at 0x000000000000006C>
>>> re.compile(r"\'%s\'" % (sys.maxint + 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
re.error: parsing "\'2147483648\'" - Capture group numbers must be less than or equal to Int32.MaxValue.
```

Originally noticed this with `fnmatch` that uses `re` internally:

```python
>>> import fnmatch
>>> fnmatch.fnmatch('', "'%s'" % sys.maxint)
False
>>> fnmatch.fnmatch('', "'%s'" % (sys.maxint + 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files\IronPython 2.7\Lib\fnmatch.py", line 43, in fnmatch
  File "c:\Program Files\IronPython 2.7\Lib\fnmatch.py", line 82, in fnmatchcase
re.error: parsing "\'2147483648\'\z" - Capture group numbers must be less than or equal to Int32.MaxValue.
```

**Comment by slozier** [comment]
My guess is the Python regex engine understands `\'` to be an escaped quote, and so equivalent to `'`. The C# regex engine that we use under the covers doesn't. The fix is probably to filter the pattern to replace `\'` with `'` before feeding it to the C# engine. Obviously, it's not a simple search & replace and may be tricky to do properly.

**Comment by slozier** [comment]
Well it looks like my guess was wrong. It seems to be scanning the pattern and assumes things like `\'123'` are capture groups. If the first character is a decimal it'll try to convert to a number. Will need to look into the C# regex syntax some more.

**Comment by pekkaklarck** [comment]
This looks related: https://docs.microsoft.com/en-us/dotnet/standard/base-types/backreference-constructs-in-regular-expressions#named-backreferences

**Comment by pekkaklarck** [comment]
Pattern like `\'999999999999999\'` causing a problem with `re.compile` isn't itself such a big problem because there isn't really need to escape the apostrophe in Python regexps. It's just that `fnmatch.translate` uses `re.escape` ([source code](https://github.com/python/cpython/blob/3.7/Lib/fnmatch.py#L127)) and `re.escape` escapes the apostrophe for no reason:

```python
>>> import fnmatch, re
>>> fnmatch.translate("'foo'")
"\\'foo\\'\\Z(?ms)"
>>> re.escape("'foo'")
"\\'foo\\'"
```

`re.escape` escaping too much was actually [changed/fixed in Python 3.7](https://bugs.python.org/issue29995). IronPython 2.7 doing the same (or just not escaping the problematic apostrophe) would be inconsistent with CPython 2.7 behavior but I doubt anyone would care.
