### ISSUE TITLE
SAX problem not working.

### ISSUE THREAD

**Issue by sebastianpszczolka** [IronLanguages/ironpython2#537]
When use simple code for xml pasring
`import xml.sax

class ABContentHandler(xml.sax.ContentHandler):
  def __init__(self):
    xml.sax.ContentHandler.__init__(self)

  def startElement(self, name, attrs):
    print("startElement '" + name + "'")
    if name == "address":
      print("\tattribute type='" + attrs.getValue("type") + "'")

  def endElement(self, name):
    print("endElement '" + name + "'")

  def characters(self, content):
    print("characters '" + content + "'")

def main(sourceFileName):
  source = open(sourceFileName)
  xml.sax.parse(source, ABContentHandler())

if __name__ == "__main__":
  main("addressbook.xml")`

I have error and I tried it with few examples from diffrent pure pythonlibrary using SAX with pyexpat.

Traceback (most recent call last):
  File "C:/Users/641/PycharmProjects/untitled/mcd.py", line 23, in <module>
  File "C:/Users/641/PycharmProjects/untitled/mcd.py", line 20, in main
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\__init__.py", line 33, in parse
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\expatreader.py", line 109, in parse
  File "C:\Program Files\IronPython 2.7\Lib\xml\sax\expatreader.py", line 310, in reset
NotImplementedError: The method or operation is not implemented.

In shot investigation I see that happen in code:
 self._parser.SetParamEntityParsing(expat.XML_PARAM_ENTITY_PARSING_UNLESS_STANDALONE)
Is there any workaround?

**Comment by slozier** [comment]
Unfortunately the `pyexpat` implementation is new (and minimal) and you hit an untested code path. In particular, the sax module has not been tested (and apparently doesn't work).

As for a workaround, the only thing I can think of would be hacking the stdlib to avoid calling problematic methods (e.g. SetParamEntityParsing and SetBase). This may be enough if you're dealing with simple XML...

**Comment by slide** [comment]
We could modify to not throw a `NotImplementedException` and just do nothing, not sure that would affect SAX specifically.

**Comment by slozier** [comment]
Yeah, I did that locally to test, unfortunately it failed on something else down the line.
