### ISSUE TITLE
pip on IronPython 2.7.9 with .NET Core 2.1

### ISSUE THREAD

**Issue by wtftc** [IronLanguages/ironpython2#564]
### Description

I am trying to use IronPython 2.7.9 on Ubuntu 16.04 with .NET Core 2.1 and am having trouble running the ensurepip command.

```
ubuntu@silver:/data/lsLocal/IronPython.2.7.9/netcoreapp2.1$ bash ipy.sh -X:Frames -m ensurepip
Traceback (most recent call last):
  File "/data/lsLocal/IronPython.2.7.9/Lib/logging/__init__.py", line 868, in emit
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 108, in format
    if self.should_color():
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 95, in should_color
    if hasattr(real_stream, "isatty") and real_stream.isatty():
IOError: [Errno 2] Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Logged from file basecommand.py, line 1
Traceback (most recent call last):
  File "/data/lsLocal/IronPython.2.7.9/Lib/logging/__init__.py", line 868, in emit
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 108, in format
    if self.should_color():
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 95, in should_color
    if hasattr(real_stream, "isatty") and real_stream.isatty():
IOError: [Errno 2] Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Logged from file req_set.py, line 1
Traceback (most recent call last):
  File "/data/lsLocal/IronPython.2.7.9/Lib/logging/__init__.py", line 868, in emit
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 108, in format
    if self.should_color():
  File "/tmp/tmpaT4f7q/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 95, in should_color
    if hasattr(real_stream, "isatty") and real_stream.isatty():
IOError: [Errno 2] Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Logged from file basecommand.py, line 1
```

It's complaining about mono assemblies not being present, but since I'm using .NET Core, it feels like I am doing something wrong.

Here's my dotnet info:

```
ubuntu@silver:/data/lsLocal/IronPython.2.7.9/netcoreapp2.1$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /data/lsLocal/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/data/lsLocal/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/data/lsLocal/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/data/lsLocal/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/data/lsLocal/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Steps to Reproduce

1. Download and unzip the IronPython 2.7.9 zip
2. Run `bash ipy.sh -X:Frames -m ensurepip` from the netcoreapp2.1 dir

**Expected behavior:**
pip should get installed

**Actual behavior:**
The error above

### Versions

You can get this information from executing `ipy -V`.
```
ubuntu@silver:/data/lsLocal/IronPython.2.7.9/netcoreapp2.1$ bash ipy.sh -V
IronPython 2.7.9 2.7.9.0 on .NET 4.0.30319.42000

```

**Comment by slide** [comment]
First of all, thank you for trying this out and filing an issue! My guess is that the Mono.Posix.NETStandard assembly is not being packaged correctly in the zip release (I assume that is how you "installed"). Can you please try downloading the nupkg file from https://www.nuget.org/api/v2/package/Mono.Posix.NETStandard/1.0.0 and grabbing the Mono.Posix.NETStandard.dll file and putting it into the same directory as ipy.sh?

**Comment by slide** [comment]
Also, please note that you don't need the `-X:Frames` argument for ipy anymore, it is on by default.

**Comment by slozier** [comment]
Still quite a bit of work to do with regards to packaging and pip on Linux. Part of the issue is that Mono.Posix.NETStandard has different binaries for each runtime. That being said, you can get something working with the following steps:
1. Grab the Mono.Posix.NETStandard.dll and libMonoPosixHelper.so files from the mono.posix.netstandard package (in runtimes/linux-x64) and put them in the netcoreapp2.1 folder.
2. Add _sysconfigdata.py to the Lib folder with the following content: `build_time_vars = {}`
3. `./ipy.sh -m ensurepip --user`
4. Then you can install your packages: `./ipy.sh -m pip install six --user`

Note that the `--user` is important otherwise ipy won't pick them up, however it will pollute your python2.7 local lib (files will end up in `~/.local/lib/python2.7`). Since it's picking up the files from the site packages from the python2.7 local lib that means you can also cheat and use Python directly to install the packages: `python2.7 -m pip install pip --user` . Note that you will still need steps 1 & 2.

Final caution, these are just hacks to get something working with the current (2.7.9) binaries, no guarantees that these workarounds are future proof...

**Comment by slide** [comment]
Can you also try setting IRONPYTHONPATH to the full path to the `Lib` directory from the zip?

**Comment by slozier** [comment]
@wtftc If you omit the `--user` it'll put the files in `Lib/python2.7/site-packages` and IronPython will not pick it up. I guess you could run a `cp ../Lib/python2.7/site-packages/* ../Lib/site-packages` after every pip install.

Note that I just tried `pip install prettytable` using ipy and it failed to install. Prettytable seems to work fine (at least a simple example) if you can get past the installation issues.

As for stuff installed via the python2.7 pip being available, it's only for stuff installed using `--user`. When you use this argument, files are installed in `~/.local/lib/python2.7`. The normal CPython pip command (without `--user`) will install in `/usr/lib/python2.7/dist-packages`.

**Comment by wtftc** [comment]
So I tried out the commands with `--user` in it, but I believe I'm hitting similar issues to what @slozier mentioned in his comment. 

```
ubuntu@silver:/data/lsLocal/IronPython.2.7.9/netcoreapp2.1$ bash ipy.sh -m ensurepip --user
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip setuptools
ubuntu@silver:/data/lsLocal/IronPython.2.7.9/netcoreapp2.1$ bash ipy.sh -m pip install prettytable --user
Collecting prettytable
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "/data/lsLocal/IronPython.2.7.9/Lib/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/utils/logging.py", line 36, in indent_log
    yield
NotImplementedError: The method or operation is not implemented.

```

Nothing is obviously throwing the `NotImplementedError` in the stack trace displayed. Can you guys help point me in the right direction to try and track down what is throwing the error?

**Comment by slozier** [comment]
I guess the package must be using bz2 for compression since it's failing in BZ2File
```C#
public new object tell() {
    throw new NotImplementedException();

    //if (this.closed) throw PythonOps.ValueError("I/O operation on closed file");
    //return base.tell();
}
```

I have no idea if the commented code is valid, will need to look into it a bit.

In the mean time, like I mentioned in my original comment, you can do `python2.7 -m pip install prettyprint --user` and you'll then be able to import in ipy.
