### ISSUE TITLE
raise "Unable to load shared library 'kernel32.dll' or one of its dependencies" on ubuntu

### ISSUE THREAD

**Issue by bluetrees886** [IronLanguages/ironpython2#578]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [yes ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

I build the ironPython with asp.net core and run with Kestrel. I need run python script in ubuntu to call darknet(yolo) which is a AI lib. When the script call get_metadata in libdarknet.so and return a c pointer ironPython throw exception message "Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory".

Stack Trace list blow

System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at IronPython.Modules.NativeFunctions.CopyMemory(IntPtr destination, IntPtr source, IntPtr Length)
   at IronPython.Modules.ModuleOps.CreateCData(IntPtr dataAddress, PythonType type)
   at InteropInvoker(IntPtr , Object , Object[] )
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at PythonApplication.PythonApp.Execute(IContainerContext context, CancellationToken cancellationToken) in J:\工作区\TFSService\Eos\SjtuAi\PythonContainer\PythonApp.cs:line 28
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      => ConnectionId:0HLJT8HECDLTL => RequestId:0HLJT8HECDLTL:00000001 RequestPath:/darknet/darknet.py
      Connection id "0HLJT8HECDLTL", Request id "0HLJT8HECDLTL:00000001": An unhandled exception was thrown by the application.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `ipy -V`.

**Comment by bluetrees886** [comment]
error script in darknet.py
...
lib = CDLL("libdarknet.so", RTLD_GLOBAL)
...
load_meta = lib.get_metadata
...
    net = load_net(b"darknet/cfg/tiny.cfg", b"darknet/data/tiny.weights", 0)
    meta = load_meta(b"darknet/cfg/coco.data")
    r = detect(net, meta, b"darknet/data/dog.jpg")

**Comment by slozier** [comment]
Looks like we're invoking `NativeFunctions.CopyMemory` without OS checks.

**Comment by slozier** [comment]
In theory https://github.com/IronLanguages/ironpython2/pull/579 should resolve this issue, however I haven't tried with your specific example.

**Comment by bluetrees886** [comment]
thanks a lots.
I'll try it later.  kernel32.dl is enabled on windows only,is it better to checking windows os than  linux or osx    in the code? Or we copy unmanaged memory by Clr without checking os?

**Comment by slide** [comment]
It will use libc's memcpy on Linux and macOS

**Comment by bluetrees886** [comment]
amazing!
It's working!
If you need, I can share my code and server.
