### ISSUE TITLE
Script execution hangs

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/ironpython2#605]
I am facing with an intermittent issue of hanging script execution in my application.
Unfortunately it is very hard to reproduce, probably related to some timing issues. When happens, CPU goes up to 25% - technically one core is fully utilized - which reminds me to an infinite loop somewhere.

I managed to collect performance data but unfortunately IronPython.pdb was not available for the executing image, so I could not drill down to the code actually casing the issue. What I found though, is the below stack where something bad happens:

![image](https://user-images.githubusercontent.com/15701860/54121730-83499280-43fb-11e9-82cb-86bbe866a6c2.png)

![image](https://user-images.githubusercontent.com/15701860/54121512-edae0300-43fa-11e9-80cc-75b85b4a52aa.png)

This looks rather weird, and I hope someone could perhaps give me a hint where to search for the root cause.

Some background information on scripts : most of my scripts are trying to load the same .Net assemblies like below example:
````Python
import re
import clr
clr.AddReferenceToFileAndPath("PGTInterfaces.dll") # Library in my project
clr.AddReferenceToFileAndPath("PGTNetworkMap.dll") # Library in my project
clr.AddReferenceToFileAndPath("Common.dll") # Library in my project
import L3Discovery
import PGT.Common
from System.Diagnostics import DebugEx, DebugLevel
from System.Net import IPAddress
````

I appreciate any hint.

Thank you.

**Comment by slozier** [comment]
Are scripts like that running on multiple threads concurrently? My only thought is that HashSet is not thread safe?

**Comment by lafrank** [comment]
Yes, they potentially can run concurrently. But most of the time no issues, only some bad timing can happen.

**Comment by lafrank** [comment]
In addition to above, I also observed a NullReferenceException occuring the same location:

Stack trace:

   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at IronPython.Runtime.PythonContext.TryLoadAssemblyFromFileWithPath(String path, Assembly& res)
   at IronPython.Runtime.PythonContext.LoadAssemblyFromFile(String file)
   at IronPython.Runtime.ClrModule.AddReferenceToFileAndPath(CodeContext context, String file)
   at IronPython.Runtime.ClrModule.AddReferenceToFileAndPath(CodeContext context, String[] files)
   at Microsoft.Scripting.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)

![image](https://user-images.githubusercontent.com/15701860/54291044-45d83700-45ac-11e9-955e-960fe5923373.png)

**Comment by slozier** [comment]
Assuming it's a threading issue, you could try adding locks around `_loadedAssemblies` calls in `PythonContext`.

Also, probably not related to your issue, but you should be careful with `clr.AddReferenceToFileAndPath` since it adds the path to `sys.path` every time you call it.
