### ISSUE TITLE
sys module has no attribute 'setprofile'

### ISSUE THREAD

**Issue by davidjcastner** [IronLanguages/ironpython2#679]
### Description

I am trying to use the 'profile' library, but when I attempted to use profile.run(...) it gives the following error:

test.py:
```py
import profile
print profile.run('print "hello world"')
```
error:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 61, in run
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 438, in run
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 442, in runctx
AttributeError: 'module' object has no attribute 'setprofile'
```

I quickly looked at Src/StdLib/Lib/profile.py, and saw that it was trying to call sys.setprofile. So I ran the following and don't see a 'setprofile' method for sys:

```
>>> import sys
>>> print dir(sys)
['__displayhook__', '__doc__', '__excepthook__', '__name__', '__package__', '__stderr__', '__stdin__', '__stdout__', '_getframe', 'api_version', 'argv', 'builtin_module_names', 'byteorder', 'call_tracing', 'callstats', 'copyright', 'displayhook', 'dllhandle', 'dont_write_bytecode', 'exc_clear', 'exc_info', 'exc_traceback', 'exc_type', 'exc_value', 'excepthook', 'exec_prefix', 'executable', 'exit', 'flags', 'float_info', 'getcheckinterval', 'getdefaultencoding', 'getfilesystemencoding', 'getrecursionlimit', 'getrefcount', 'getsizeof', 'gettrace', 'getwindowsversion', 'hexversion', 'implementation', 'long_info', 'maxint', 'maxsize', 'maxunicode', 'meta_path', 'modules', 'path', 'path_hooks', 'path_importer_cache', 'platform', 'prefix', 'ps1', 'ps2', 'py3kwarning', 'setcheckinterval', 'setrecursionlimit', 'settrace', 'stderr', 'stdin', 'stdout', 'subversion', 'version', 'version_info', 'warnoptions', 'winver']
```

### Steps to Reproduce

1. run the following:

```sh
import profile
print profile.run('print "hello world"')
```

**Expected behavior:** The profiler should run and print out usage stats.

**Actual behavior:** Attribute Error: 'module' object has no attribute 'setprofile'

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 61, in run
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 438, in run
  File "C:\Program Files\IronPython 2.7\Lib\profile.py", line 442, in runctx
AttributeError: 'module' object has no attribute 'setprofile'
```

### Versions

IronPython 2.7.9 2.7.9.0 on .NET 4.0.30319.42000

**Comment by slozier** [comment]
Related issues: https://github.com/IronLanguages/main/issues/264
