### ISSUE TITLE
Using pip fails with `IndexError: index out of range: -1`

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#71]
_From @pekkaklarck on January 30, 2017 11:57_

After installing IronPython 2.7.7 and running `ipy -X:Frames -m ensurepip`, trying to install a package or just check the installed pip version fails like this:

```
C:\Windows\system32>ipy -X:Frames -m pip install robotframework
Unhandled exception:
Traceback (most recent call last):
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 26, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\__init__.py", line 27, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 74, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4715, in <module>
IndexError: index out of range: -1
```
Same problem if I just try to check installed pip version with `--version` or run the installed `pip.exe` directly.

_Copied from original issue: IronLanguages/main#1572_

**Comment by slide** [comment]
_From @slozier on February 6, 2017 13:1_

I haven't been able to reproduce this using the steps provided (install IronPython 2.7.7, run ensure pip and then "try to do anything with pip").

After hitting the same issue while investigating #1573 I did boil it down to a simple repro case which does not invlove pyparsing: https://github.com/IronLanguages/main/issues/1573#issuecomment-277086607

**Comment by lostmsu** [comment]
Heads up, I get the same after upgrading pip to 9.0.1 and trying to install Tensorflow.

**Comment by slide** [comment]
Please don't upgrade pip, we test with a specific version of pip.

**Comment by lostmsu** [comment]
@slide , pip <= 9.0 can't see Tensorflow.

**Comment by slide** [comment]
Pip > what we bundle isn't guaranteed to work. Even the one we bundle still causes issues for some people.

**Comment by lostmsu** [comment]
@slide , it's OK. If that becomes critical, I can debug myself.

**Comment by pekkaklarck** [comment]
Could you work with pip devs about getting pip tested on IronPython automatically? AFAIK they already test with PyPy, and adding IronPython (and Jython) into the mix shouldn't be overly complicated.

**Comment by slide** [comment]
The -1 issue is because pyparsing is using the traceback and f_back to determine function names and things like that. The f_back property is not getting filled in for some reason. This needs to be debugged.

**Comment by slide** [comment]
Well, the newer versions of pip don't work with IronPython 2.7.8, we should create a new issue to track that.
