### ISSUE TITLE
Installing webrtcvad python module , results in error

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [IronLanguages/ironpython2#740]
* [ ] Are you running the latest version? Yes I am using version 2.7.10
* [ ] Are you reporting to the correct repository? Yes
* [ ] Did you perform a cursory search? Yes I did searched on stackoverflow for the same

### Description

I am trying to install py-webrtcvad module using command
**ipy -X:Frames -m pip install webrtcvad**

It results in the below error :

    **Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\setuptools\__init__.py", line 170, in <module>
    TypeError: a new-style class can't have only classic bases**

### Steps to Reproduce

Used below command 

1: ipy -X:Frames -m ensurepip
2. ipy -X:Frames -m pip install webrtcvad 

and it resulted in this error

### Versions
IronPython 2.7.10 2.7.10.0 on .NET 4.0.30319.42000

**Comment by slozier** [comment]
Duplicate of https://github.com/IronLanguages/ironpython2/issues/624

**Comment by slozier** [comment]
Workaround for the issue is patching `site-packages\setuptools\__init__.py` with the following (add the two lines with `__metaclass__`):
```Python
del __metaclass__

class Command(_Command):
    # ...

__metaclass__ = type
```

**Comment by harmandeepsinghkalsi** [comment]
@slozier  I changed the __init__.py as you mentioned , I got this below error 

![image](https://user-images.githubusercontent.com/10211042/92462468-272a1f00-f1e8-11ea-9406-a949a79c80c8.png)

Am I missing something here?

**Comment by slozier** [comment]
You could avoid that particular issue by commenting out the `patch_for_msvc_specialized_compiler()` in `setuptools/monkey.py` (as is done in https://github.com/IronLanguages/ironpython2/commit/71d7e7a3108e059a17abaa7e535f4f3fa879188e).

Unfortunately, having looked at `webrtcvad`, it looks like wants to compile a C extension module, and that will not work with IronPython.

**Comment by harmandeepsinghkalsi** [comment]
@slozier  , thank you for confirming on this .
