### ISSUE TITLE
Concurrent lookups of instances on a class sometimes result in NullReferenceException

### ISSUE THREAD

**Issue by mickp** [IronLanguages/ironpython2#771]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you perform a cursory search?

### Description

When object instances are defined on a class, concurrent lookups of that instance sometimes produce a `NullReferenceException` in `PythonTypeUserDescriptorSlot.GetValue`.

### Steps to Reproduce

Run the following in C# Interactive. It eventually fails with a `NullReferenceException`.

```
#r "Microsoft.Scripting"
#r "IronPython"

using System;
using IronPython.Hosting;
using IronPython.Runtime;
using IronPython;
using Microsoft.Scripting.Hosting;
using Microsoft.Scripting;

var engine = Python.CreateEngine();
var scope = engine.CreateScope();
engine.SetSearchPaths(new[] { @"C:\Program Files\IronPython 2.7\Lib\" });

string script = @"
import threading
from multiprocessing.pool import ThreadPool


class Member(object):
    alpha = 0
    beta = 1


class Thing(object):
    member = Member
    member_instance = Member()


test_thing = Thing()


def query(trigger_event):
    trigger_event.wait()
    return [test_thing.member_instance for _ in range(10)][-1]


def single_test(number_of_threads):
    trigger = threading.Event()

    pool = ThreadPool(number_of_threads)
    results = [pool.apply_async(query, [trigger]) for i in range(number_of_threads)]
    trigger.set()
    [r.get() for r in results]
    pool.close()
    pool.join()


# Including the next line prevents NullReferenceExceptions in the threaded queries.
# print test_thing.member_instance

single_test(16)
";

while (true) {
    engine.Execute(script);
}

```

**Expected behavior:** Concurrent lookups each return the object instance, always.

**Actual behavior:** Concurrent lookups occasionally produce a `NullReferenceException`.
```
System.NullReferenceException: Object reference not set to an instance of an object.
  + Microsoft.Scripting.Interpreter.ThrowInstruction.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.Interpreter.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.LightLambda.Run3<T0, T1, T2, TRet>(T0, T1, T2)
  + System.Dynamic.UpdateDelegates.UpdateAndExecute3<T0, T1, T2, TRet>(System.Runtime.CompilerServices.CallSite, T0, T1, T2)
  + IronPython.Runtime.Method.MethodBinding.SelfTarget(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, object)
  + System.Dynamic.UpdateDelegates.UpdateAndExecute2<T0, T1, TRet>(System.Runtime.CompilerServices.CallSite, T0, T1)
  + IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.Interpreter.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.LightLambda.Run2<T0, T1, TRet>(T0, T1)
  + System.Dynamic.UpdateDelegates.UpdateAndExecute3<T0, T1, T2, TRet>(System.Runtime.CompilerServices.CallSite, T0, T1, T2)
  + IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.Interpreter.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
  + Microsoft.Scripting.Interpreter.LightLambda.Run1<T0, TRet>(T0)
  + IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Microsoft.Scripting.Runtime.Scope)
  + Microsoft.Scripting.Hosting.ScriptSource.Execute()
```

### Versions

2.7.11 (2.7.11.1000)
[.NETFramework,Version=v4.5 on .NET Framework 4.8.4300.0 (64-bit)]

**Comment by mickp** [comment]
A more useful stacktrace from an application where we first hit this:

```   
   at IronPython.Runtime.Types.PythonTypeUserDescriptorSlot.GetValue(CodeContext context, Object instance, PythonType owner)
   at IronPython.Runtime.Types.GetMemberDelegates.UserSlotDict(CallSite site, Object self, CodeContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.DynamicGetMemberExpression.GetMemberInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at IronPython.Compiler.PythonCallTargets.OriginalCallTarget4(PythonFunction function, Object arg0, Object arg1, Object arg2, Object arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at IronPython.Runtime.Method.MethodBinding`3.SelfTarget(CallSite site, CodeContext context, Object target, T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at IronPython.Compiler.Ast.CallExpression.Invoke3Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run6[T0,T1,T2,T3,T4,T5,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at CallSite.Target(Closure , CallSite , CodeContext , Object , Object , Object )
   at _thread_operation$718(Closure , PythonFunction , Object , Object , Object ).
```

**Comment by slozier** [comment]
@mickp Can you test if https://github.com/IronLanguages/ironpython2/pull/772 resolves your issue?

**Comment by mickp** [comment]
@slozier Thanks for the quick response.
#772:
* does not resolve the issue on .Net Framework 4.8;
* does appear to fix it on .Net Core 3.1.

**Comment by mickp** [comment]
@slozier Apologies - I'm still seeing failures on 4.8. I don't see a DLL build for 4.8, though, so it could be that. It  is definitely resolved in 3.1.

**Comment by mickp** [comment]
Rebuilt and double checked the paths for the references. It's using the newly-build IronPython.dll for Framework 4.8, and still failing, although the failure rate seems to be lower.

A colleague has done his own tests and sees the same: resolved in Core 3.1, not in FW.

**Comment by slozier** [comment]
@mickp Hmm, I'm not getting a failure with the sample program here. Are you sure it's not picking up the old IronPython assembly from the GAC? I believe the msi installer has the option to install to the GAC on by default.

**Comment by danielbanda** [comment]
I was helping @mickp troubleshoot this issue. 

We cloned the repo and added tests project in IronPython's solution. So, no, we were not using GAC assemblies but project references.

I hope this helps.

**Comment by mickp** [comment]
Just to make sure, I cleared out all IronPython-related DLLs from the GAC. I still see the failures under FW4.8.

**Comment by slozier** [comment]
Hmm, I haven't been able to reproduce the failure with 4.8 over here, but I guess it was still possible to end up in inconsistent state. Anyway, I pushed an update to the fix.

**Comment by mickp** [comment]
@slozier - You were absolutely right: it appears there are multiple GAC locations. I dumped debugging output, and saw that the tests are pulling FW4.8 from *another* folder under `%windir%`, rather than those set in the project references (which I checked before). 

Your fix resolves the issue in both .Net versions.

**Comment by slozier** [comment]
@mickp Thanks for the update. Which version of the fix did you adopt (so I know which one to merge)?

**Comment by mickp** [comment]
@slozier I just retested both, now I know my tests are pulling the correct assemblies! 
The first commit (8ff8c3db5de9c860163a2dde7ee7967b38a8d14c) resolves the issue in both Framework and Core.
