### ISSUE TITLE
ArgumentNullException thrown when underlying c# delegate throws an exception

### ISSUE THREAD

**Issue by JimmyHeartbreaker** [IronLanguages/ironpython2#776]
Version: 2.7.10
.Net Framework 4.7.2

When throwing an exception inside a C# delegate the following error is occasionally thrown.

System.ArgumentNullException: Value cannot be null.
Parameter name: del
   at System.Reflection.RuntimeReflectionExtensions.GetMethodInfo(Delegate del)
   at IronPython.Runtime.PythonDynamicStackFrame.GetMethod(CodeContext context, FunctionCode funcCode)
   at IronPython.Runtime.PythonDynamicStackFrame..ctor(CodeContext context, FunctionCode funcCode, Int32 line)
   at IronPython.Runtime.Operations.PythonOps.UpdateStackTrace(Exception e, CodeContext context, FunctionCode funcCode, Int32 line)
   at Microsoft.Scripting.Interpreter.ActionCallInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at Microsoft.Scripting.Hosting.CompiledCode.Execute[T](ScriptScope scope)

It is difficult to reproduce because it is intermittent.
We are caching the compiled script so it could be something at that stage. This would explain the intermittent behaviour the way we are seeing it.

it is important that we catch the correct exception in the c# calling Execute.

Not sure when this started happening. It wasnt happening in earlier versions. Nothing in our code explains this behaviour.

Would there be any reason 2.7.11 would not have this problem?

**Comment by slozier** [comment]
What version were you running on before? I can't think of any changes since the 2.7.10 release that might resolve this...

**Comment by JimmyHeartbreaker** [comment]
> What version were you running on before? I can't think of any changes since the 2.7.10 release that might resolve this...

unfortunately Im not sure when the issue began and weve updated a couple of times in the last 6-12 months.
I see the DLR version goes from 1.2.3 -> 1.3 in the 2.7.11 release.

**Comment by slozier** [comment]
There have been quite a few changes since 2.7.7 so without any code to reproduce the issue it's hard to say if/when a bug might have been introduced.

The major bump in the version number of the DLR is due to a breaking change (removal of zlib). I mean, you can try 2.7.11, but I can't think of any changes that would relate the stack trace above.

**Comment by JimmyHeartbreaker** [comment]
ill try to recreate a minimal application to reproduce it. Thanks.

**Comment by JimmyHeartbreaker** [comment]
> There have been quite a few changes since 2.7.7 so without any code to reproduce the issue it's hard to say if/when a bug might have been introduced.
> 
> The major bump in the version number of the DLR is due to a breaking change (removal of zlib). I mean, you can try 2.7.11, but I can't think of any changes that would relate the stack trace above.

I struggled to get a minimal application reproducing the issue. I rolled back to 2.7.5 and that fixed the issue.

**Comment by JimmyHeartbreaker** [comment]
My issue was fixed in version 3.4

**Comment by Dunge** [comment]
Cool. Any chance of getting the fix backported to IronPython2? I have too many existing python2 script to convert to IronPython3.

**Comment by JimmyHeartbreaker** [comment]
I'm sorry, i have no idea which change fixed it
