### ISSUE TITLE
hashlib module ironpython 2.7.3 error line 160 and 161

### ISSUE THREAD

**Issue by dronov-dmitry** [IronLanguages/ironpython2#787]
here is error in ironpython 2.7.3 with dynamo
https://prnt.sc/1ni0vik
in module hashlib
line 160 and 161
https://prnt.sc/1ni27a6
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\random.py", line 49, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\hashlib.py", line 160, in <module>
TypeError: sequence item 0: expected bytes or byte array, str found

I just del "b" and it work
https://prnt.sc/1ni2x34

**Comment by slozier** [comment]
Thanks for the report, this particular issue (`b"".join(chr(x ^ 0x5C) for x in range(256))`) was fixed in IronPython 2.7.5. I would suggest upgrading to a more recent release if possible.
