### ISSUE TITLE
Serializing failed due to missing parameterless constructor

### ISSUE THREAD

**Issue by matthiasburger** [IronLanguages/ironpython2#799]
I wanted to use the XML-Serializer from .NET but I can't. This could be a problem that often can appear: missing parameterless constructor

```python
import clr
import clrtype

clr.AddReference('System.Xml')
clr.AddReference('System.IO')

from System.Xml.Serialization import XmlElementAttribute, XmlSerializer
from System.IO import Stream, FileStream, FileMode


class NugetPackage(object):
    __metaclass__ = clrtype.ClrClass
    XmlElement = clrtype.attribute(XmlElementAttribute)

    def __init__(): pass ## doesn't work either....

    def __init__(self): ## isn't this one parameterless?
        self._id = None
        self._version = None
        self._repository = None
        self._authors = None
        self._owners = None
        self._tags = None
        self._description = None
        self._dependencies = []

    @staticmethod
    def read_info(nuspec):
        spec_file = open(nuspec, mode='r')
        whole_text = spec_file.read()
        spec_file.close()

        nuget_package_type = clr.GetClrType(type(NugetPackage))
        serializer = XmlSerializer(nuget_package_type)

        with FileStream(nuspec, FileMode.Open) as reader:
            return serializer.Deserialize(reader)

    @XmlElement('Id')
    def id(self, value):
        self._id = value
```

I tried everything.. but nothing works here. Any idea?

**Comment by slozier** [comment]
I think you've got the wrong type, should probably be:
```py
nuget_package_type = clr.GetClrType(NugetPackage)
```
Although then it seems to fail on something else...

**Comment by matthiasburger** [comment]
ahh that makes sense :)
still, it cannot reflect the type :/

```python
Traceback (most recent call last):
  File "C:/Users/m.burger/PycharmProjects/ironwasp/main.py", line 18, in <module>
  File "C:/Users/m.burger/PycharmProjects/ironwasp/main.py", line 12, in print_hi
  File "C:\Users\m.burger\PycharmProjects\ironwasp\tools\nuget\package_manager.py", line 28, in read_info
SystemError: Fehler beim Reflektieren des Typs 'NugetPackage'.
```

**Comment by slozier** [comment]
Stack trace when running with `-X:ExceptionDetail`:
```
There was an error reflecting type 'NugetPackage'.
ImportTypeMapping at offset 2347 in file:line:column <filename unknown>:0:0

ImportElement at offset 175 in file:line:column <filename unknown>:0:0

ImportTypeMapping at offset 133 in file:line:column <filename unknown>:0:0

.ctor at offset 437 in file:line:column <filename unknown>:0:0

   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Hosting.PythonCommandLine.RunFileWorker(String fileName)
   at IronPython.Hosting.PythonCommandLine.RunFile(String fileName)
   at System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type type, String memberInfo)
   at System.Xml.Serialization.TypeScope.ImportTypeDesc(Type type, MemberInfo memberInfo, Boolean directReference)
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.StructModel.GetFieldModel(FieldInfo fieldInfo)
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
SystemError: There was an error reflecting type 'NugetPackage'.
```
