### ISSUE TITLE
implement the _tkinter module in the IronPython core

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#80]
_From @mdengusiak on November 11, 2016 11:4_

Would be possible to implement the _tkinter module in the IronPython core?
or there is any way to get it working?

_Copied from original issue: IronLanguages/main#1537_

**Comment by slide** [comment]
Would you want interfacing with Tcl/Tk, or just a wrapper around another GUI library?

**Comment by slide** [comment]
_From @mdengusiak on November 11, 2016 12:58_

I want to be able import Turtle module so can show young people and children that programming is fun and we can combine simple and more complex scripts from same environment which will be Dynamo BIM for Revit.

**Comment by slide** [comment]
_From @mdengusiak on November 14, 2016 10:25_

@slide What do you think about getting Tkinter?

**Comment by slide** [comment]
I think it would probably happen on the ironpython3 release tree instead of here, but it wouldn't be soon.

**Comment by 15871722713** [comment]
I have the same issue,  how can i import this moule? 
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\Tkinter.py", line 39, in <module>
ImportError: No module named _tkinter

**Comment by slide** [comment]
It's not available. The current canonical ways to develop GUI applications with IronPython are System.Windows.Forms and WPF
