### ISSUE TITLE
Tracing does not work

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#99]
_From @jpmaterial on May 18, 2016 12:39_

The example for programmatic tracing with the trace module as given in the docs (https://docs.python.org/2.7/library/trace.html#programmatic-interface) works for me only after some hacking (see bottom).

Without the hacks I got
Traceback (most recent call last):

  File "./trace_test.py", line 38, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 510, in run
  File "<string>", line 1, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 607, in globaltrace_lt

AttributeError: 'NoneType' object has no attribute 'get'

With only the globaltrace_lt() hack I got:

Traceback (most recent call last):

  File "./trace_test.py", line 42, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 328, in write_results
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 406, in find_lines
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 397, in find_lines_from_code
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 448, in find_executable_linenos
  File "C:\MinGW\msys\1.0\bin\Lib\dis.py", line 184, in findlinestarts

NotImplementedError

I'm using PythonContext 2.7.5.0 on .NET 4.0.30319.42000

My hacks:

```
def main():
    print 'hello world'


import sys
import trace


import dis

def fake_globaltrace_lt(self,frame,why,arg):
    return self.localtrace

dis.real_findlinestarts=dis.findlinestarts

def fake_findlinestarts(code):
    if 'co_lnotab' in dir(code):
        dis.real_findlinestarts(code)
    else:
        print dir(code)
        yield (0,0)

dis.findlinestarts=fake_findlinestarts

trace.Trace.globaltrace_lt=fake_globaltrace_lt


# create a Trace object, telling it what to ignore, and whether to
# do tracing or line-counting or both.
tracer = trace.Trace(
    ignoredirs=[sys.prefix, sys.exec_prefix],
    trace=1,
    count=1)

# run the new command using the given tracer
tracer.run('main()')

# make a report, placing output in the current directory
r = tracer.results()
r.write_results(show_missing=True, coverdir="cover")

```

_Copied from original issue: IronLanguages/main#1296_

**Comment by slide** [comment]
@markusschaber You mentioned you guys use tracing in your stuff, can you take a look at this?

**Comment by slide** [comment]
@kunom Any comments?

**Comment by slide** [comment]
_From @kunom on October 19, 2016 17:45_

The first issue is a TracebackFrame instance that is constructed with a `scopeCallback` argument instead of a `globals` PythonDictionary, but the dictionary returned by scopeCallback does hold `null` as value for "$globalContext".

**Comment by slide** [comment]
_From @kunom on October 24, 2016 6:47_

It is actually a systematic issue that "$globalContext" is not initialized at the time of the "call" trace event when entering a function. Only on subsequent "line" trace events.

**Comment by strongly-typed** [comment]
I am able to reproduce the `AttributeError: 'NoneType' object has no attribute 'get'` with a simple
```
print('hello world')
```
program when using `trace`:

```
 'C:\Program Files\IronPython 2.7\ipy.exe' -X:Tracing -X:FullFrames -m trace --trace hello_world.py
 --- modulename: hello_world, funcname: <module>
hello world
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 187, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 819, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 807, in main
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 516, in runctx
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 598, in globaltrace_lt
AttributeError: 'NoneType' object has no attribute 'get'
```

Unfortunately, I am not able to use the hack from @jpmaterial
```
'C:\Program Files\IronPython 2.7\ipy.exe' -X:Tracing -X:FullFrames hello_world.py
hello_world.py(2):     print('hello world')
hello world
trace.py(80):         sys.settrace(None)
trace.py(81):         threading.settrace(None)
Traceback (most recent call last):
  File "hello_world.py", line 39, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 323, in write_results
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 205, in fullmodname
IndexError: index out of range: 14
```

Strangely, the results differ between `ipy.exe` and `ipy32.exe`

```
'C:\Program Files\IronPython 2.7\ipy32.exe' -X:Tracing -X:FullFrames hello_world.py
hello_world.py(2):     print('hello world')
hello world
trace.py(80):         sys.settrace(None)
trace.py(81):         threading.settrace(None)
Traceback (most recent call last):
  File "hello_world.py", line 39, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 328, in write_results
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 448, in find_executable_linenos
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 406, in find_lines
  File "C:\Program Files\IronPython 2.7\Lib\trace.py", line 397, in find_lines_from_code
  File "hello_world.py", line 17, in fake_findlinestarts
TypeError: Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.BlockExpression'.
```

Any progress on tracing?

**Comment by slozier** [comment]
The difference in failure between the 32 and 64-bit appears to be related to the order of dictionary elements:
```
>>> {'B': {}, 'A': {}} # 32-bit
{'B': {}, 'A': {}}
```
```
>>> {'B': {}, 'A': {}} # 64-bit
{'A': {}, 'B': {}}
```
So you're getting different failures depending on what element is hit first.

It looks like you could "fix" the `IndexError` by adding `sys.path.remove(__file__)` to the hack. I'm not sure why `__file__` is included in `sys.path`, I will have to look into this...

The `TypeError` appears to only occur when both `Tracing` and `FullFrames` are set. It looks like you can avoid this issue as well by tweaking the hack.

The "corrected" hack would be:
```Python
def main():
    print 'hello world'

import sys
sys.path.remove(__file__)

import dis
try:
    (lambda: None).__code__.co_lnotab
except:
    def fake_findlinestarts(code):
        yield (0,0)
    dis.findlinestarts=fake_findlinestarts

import trace
def fake_globaltrace_lt(self,frame,why,arg):
    return self.localtrace
trace.Trace.globaltrace_lt=fake_globaltrace_lt

# create a Trace object, telling it what to ignore, and whether to
# do tracing or line-counting or both.
tracer = trace.Trace(
    ignoredirs=[sys.prefix, sys.exec_prefix],
    trace=1,
    count=1)

# run the new command using the given tracer
tracer.run('main()')

# make a report, placing output in the current directory
r = tracer.results()
r.write_results(show_missing=True, coverdir="cover")
```

> Any progress on tracing?

No work has been done in this area recently.
